// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Repository.Database;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20251005065036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("senha");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cargo");

                    b.HasKey("Id")
                        .HasName("pk_aluno");

                    b.ToTable("aluno", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "UsuarioTeste1@aprendanave.com",
                            Nome = "UsuarioTeste1",
                            Senha = "SenhaUsuarioTeste123",
                            cargo = "Aluno"
                        });
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoModuloProgresso", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    b.Property<int>("IdModulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_modulo");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer")
                        .HasColumnName("modulo_id");

                    b.Property<string>("StatusProgresso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_progresso");

                    b.HasKey("IdAluno", "IdModulo")
                        .HasName("pk_aluno_modulo_progresso");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_aluno_modulo_progresso_aluno_id");

                    b.HasIndex("ModuloId")
                        .HasDatabaseName("ix_aluno_modulo_progresso_modulo_id");

                    b.ToTable("aluno_modulo_progresso", "public");
                });

            modelBuilder.Entity("server.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("professor");

                    b.HasKey("Id")
                        .HasName("pk_curso");

                    b.ToTable("curso", "public");
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("Nivel")
                        .HasMaxLength(25)
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuantidadeAulas")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_aulas");

                    b.Property<int>("QuantidadeHoras")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_horas");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("ix_modulo_curso_id");

                    b.ToTable("modulo", "public");
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoModuloProgresso", b =>
                {
                    b.HasOne("server.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_modulo_progresso_aluno_aluno_id");

                    b.HasOne("server.Domain.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_modulo_progresso_modulo_modulo_id");

                    b.Navigation("Aluno");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("server.Domain.Entities.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modulo_curso_curso_id");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("server.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
