// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Repository.Database;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20251019182755_TesteFinal")]
    partial class TesteFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_aluno");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoModuloProgresso", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    b.Property<int>("IdModulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_modulo");

                    b.Property<int>("StatusProgresso")
                        .HasColumnType("integer")
                        .HasColumnName("status_progresso");

                    b.HasKey("IdAluno", "IdModulo")
                        .HasName("pk_aluno_modulo_progresso");

                    b.HasIndex("IdModulo")
                        .HasDatabaseName("ix_aluno_modulo_progresso_id_modulo");

                    b.ToTable("aluno_modulo_progresso", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("professor");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_curso");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("Nivel")
                        .HasMaxLength(25)
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuantidadeAulas")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_aulas");

                    b.Property<int>("QuantidadeHoras")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_horas");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("ix_modulo_curso_id");

                    b.ToTable("modulo", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoModuloProgresso", b =>
                {
                    b.HasOne("server.Domain.Entities.Aluno", "Aluno")
                        .WithMany("AlunoModuloProgresso")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_modulo_progresso_aluno_id_aluno");

                    b.HasOne("server.Domain.Entities.Modulo", "Modulo")
                        .WithMany("AlunoModuloProgressos")
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_modulo_progresso_modulo_id_modulo");

                    b.Navigation("Aluno");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("server.Domain.Entities.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modulo_curso_curso_id");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("server.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("AlunoModuloProgresso");
                });

            modelBuilder.Entity("server.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("AlunoModuloProgressos");
                });
#pragma warning restore 612, 618
        }
    }
}
