// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Repository.Database;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20260108042456_StatusCurso")]
    partial class StatusCurso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_aluno");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoAulaProgresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<int>("AulaId")
                        .HasColumnType("integer")
                        .HasColumnName("aula_id");

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    b.Property<int>("IdAula")
                        .HasColumnType("integer")
                        .HasColumnName("id_aula");

                    b.Property<int>("IdModulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_modulo");

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer")
                        .HasColumnName("modulo_id");

                    b.HasKey("Id")
                        .HasName("pk_aluno_aula_progresso");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_aluno_aula_progresso_aluno_id");

                    b.HasIndex("AulaId")
                        .HasDatabaseName("ix_aluno_aula_progresso_aula_id");

                    b.HasIndex("ModuloId")
                        .HasDatabaseName("ix_aluno_aula_progresso_modulo_id");

                    b.ToTable("aluno_aula_progresso", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoModuloProgresso", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    b.Property<int>("IdModulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_modulo");

                    b.Property<int>("StatusProgresso")
                        .HasColumnType("integer")
                        .HasColumnName("status_progresso");

                    b.HasKey("IdAluno", "IdModulo")
                        .HasName("pk_aluno_modulo_progresso");

                    b.HasIndex("IdModulo")
                        .HasDatabaseName("ix_aluno_modulo_progresso_id_modulo");

                    b.ToTable("aluno_modulo_progresso", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int?>("Duracao")
                        .HasColumnType("integer")
                        .HasColumnName("duracao");

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer")
                        .HasColumnName("modulo_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<string>("VideoYoutubeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_youtube_id");

                    b.HasKey("Id")
                        .HasName("pk_aula");

                    b.HasIndex("ModuloId")
                        .HasDatabaseName("ix_aula_modulo_id");

                    b.ToTable("aula", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("professor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_curso");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.DesafioJcc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_aluno");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.HasKey("Id")
                        .HasName("pk_desafio_jcc");

                    b.ToTable("desafio_jcc", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.GuestUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contato");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_guest_user");

                    b.ToTable("guest_user", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("Nivel")
                        .HasMaxLength(25)
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Playlist")
                        .HasColumnType("text")
                        .HasColumnName("playlist");

                    b.Property<int>("QuantidadeAulas")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_aulas");

                    b.Property<int>("QuantidadeHoras")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_horas");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("ix_modulo_curso_id");

                    b.ToTable("modulo", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_aluno");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.HasKey("Id")
                        .HasName("pk_ranking");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_ranking_aluno_id");

                    b.ToTable("ranking", (string)null);
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoAulaProgresso", b =>
                {
                    b.HasOne("server.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_aula_progresso_aluno_aluno_id");

                    b.HasOne("server.Domain.Entities.Aula", "Aula")
                        .WithMany()
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_aula_progresso_aula_aula_id");

                    b.HasOne("server.Domain.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_aula_progresso_modulo_modulo_id");

                    b.Navigation("Aluno");

                    b.Navigation("Aula");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("server.Domain.Entities.AlunoModuloProgresso", b =>
                {
                    b.HasOne("server.Domain.Entities.Aluno", "Aluno")
                        .WithMany("AlunoModuloProgresso")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_modulo_progresso_aluno_id_aluno");

                    b.HasOne("server.Domain.Entities.Modulo", "Modulo")
                        .WithMany("AlunoModuloProgressos")
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_modulo_progresso_modulo_id_modulo");

                    b.Navigation("Aluno");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("server.Domain.Entities.Aula", b =>
                {
                    b.HasOne("server.Domain.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aula_modulo_modulo_id");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("server.Domain.Entities.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modulo_curso_curso_id");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("server.Domain.Entities.Ranking", b =>
                {
                    b.HasOne("server.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Rankings")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ranking_aluno_aluno_id");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("server.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("AlunoModuloProgresso");

                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("server.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("server.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("AlunoModuloProgressos");
                });
#pragma warning restore 612, 618
        }
    }
}
